// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZsqQpjXnxTwn6WKcILOvzzLkLtk5SjsE',
    appId: '1:512164057072:web:0c7ef9e3e09dfd74aa5735',
    messagingSenderId: '512164057072',
    projectId: 'barbapp-ff512',
    authDomain: 'barbapp-ff512.firebaseapp.com',
    storageBucket: 'barbapp-ff512.firebasestorage.app',
    measurementId: 'G-JF0TWB7G8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaMCScARsCNpPWgoCLLRSTjscmITcsYFU',
    appId: '1:512164057072:android:8f3430f3e7d6fecdaa5735',
    messagingSenderId: '512164057072',
    projectId: 'barbapp-ff512',
    storageBucket: 'barbapp-ff512.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF-WpUJjqDmlSiKG8shUfeiR18N4DaMzA',
    appId: '1:512164057072:ios:de0ddcdfba6918d4aa5735',
    messagingSenderId: '512164057072',
    projectId: 'barbapp-ff512',
    storageBucket: 'barbapp-ff512.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF-WpUJjqDmlSiKG8shUfeiR18N4DaMzA',
    appId: '1:512164057072:ios:de0ddcdfba6918d4aa5735',
    messagingSenderId: '512164057072',
    projectId: 'barbapp-ff512',
    storageBucket: 'barbapp-ff512.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZsqQpjXnxTwn6WKcILOvzzLkLtk5SjsE',
    appId: '1:512164057072:web:4ec5ea494188ba6eaa5735',
    messagingSenderId: '512164057072',
    projectId: 'barbapp-ff512',
    authDomain: 'barbapp-ff512.firebaseapp.com',
    storageBucket: 'barbapp-ff512.firebasestorage.app',
    measurementId: 'G-883KMNWVZ5',
  );
}
